### ISSUE TITLE
Seems to lose start of week setting

### ISSUE THREAD

**Issue by ottsch** [TfTHacker/obsidian42-jump-to-date#10]
No matter what I try, it always turns the “First day of the week on calendar is Sunday” back on … :cry:

**Comment by TfTHacker** [comment]
This is unusual. I have this working on a few devices. Maybe uninstall the plugin and make sure the folder under plugins for jump-to-date does not exist. I say this, because it seems its not persisting back to a file called data.json in the plugin folder.

One other option is a sync conflict. You change it on one device, and the other devices pushes back the change. I doubt this, but mention it for troubleshooting.

**Comment by TfTHacker** [comment]
I am curious if this resolved the issue?

**Comment by wenlzhang** [comment]
I also observed this issue for quite a few times. I will try uninstalling it and see if it resolves the issue.

**Comment by KierenB** [comment]
FWIW I also have this issue. I can replicate it simply by fully closing and re-opening the app. I'm on Mac and use sync, but the settings are not synced. I have tried uninstalling the plugin (and confirming folder is deleted) then reinstalling, but no matter what, every time I re-open the app the setting has defaulted to Sun.
